figure;

eq = { ...
    '\frac{i^4\,w\,\left(-8\,R\,\pi \,\Omega \left(R\right)\,{\mathrm{Bz}}^2\,{\mathrm{Kz}}^4\,p\,\frac{\partial }{\partial R} \Omega \left(R\right)+{\mathrm{Bz}}^4\,{\mathrm{Kr}}^2\,{\mathrm{Kz}}^4\,i^2+{\mathrm{Bz}}^4\,{\mathrm{Kz}}^6\,i^2-8\,\pi \,{\mathrm{Bz}}^2\,{\mathrm{Kr}}^2\,{\mathrm{Kz}}^2\,i^2\,p\,w^2-8\,\pi \,{\mathrm{Bz}}^2\,{\mathrm{Kz}}^4\,i^2\,p\,w^2+16\,\pi ^2\,{\mathrm{Kr}}^2\,i^2\,p^2\,w^4+16\,\pi ^2\,{\mathrm{Kz}}^2\,i^2\,p^2\,w^4+16\,\pi ^2\,{\mathrm{Kz}}^2\,k^2\,p^2\,w^2\right)}{16\,p^3\,\pi ^2}'};

eq_full = strjoin(eq, '');

annotation('textbox',[0 0 1 1], ...
    'String',['$' eq_full '$'], ...
    'Interpreter','latex', ...
    'FontSize',14, ...
    'EdgeColor','none');

axis off
